language: node_js
node_js:
    - "8"

os:
    - osx
    - linux

before_install:
    - if [ $TRAVIS_OS_NAME == "linux" ]; then
        apt-get update && apt-get install -y xvfb
        export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
        sh -e /etc/init.d/xvfb start;
        sleep 3;
      fi

install:
    - npm install
    - npm run vscode:prepublish

script:
    - npm test --silent
